name: build-and-push-image

on:
  workflow_dispatch:
    inputs:
      registryName:
        description: 'ACR name'
        required: true
        default: 'pltengacr01-dcg6ewfbbscthnfr'
      repositoryName:
        description: 'Container repository name'
        required: true
        default: 'ade/terraform'
      tag:
        description: 'Image tag'
        required: true
        default: '0.0.1'
permissions:
  id-token: write
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      registryName: ${{ github.event.inputs.registryName }}
      repositoryName: ${{ github.event.inputs.repositoryName }}
      tag: ${{ github.event.inputs.tag }}

    steps:
    - name: 'Az CLI login'
      uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
    - name: 'Login to Specified ACR'
      run: az acr login -n $registryName
      
    - uses: actions/checkout@v4
    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag "$registryName.azurecr.io/$repositoryName:$tag"

    - name: 'Push the Docker Image'
      run: docker push "$registryName.azurecr.io/$repositoryName:$tag"
